/// Shared, app-wide translations. Generated by intl_utils (`melos intl`).
///
/// Use via `context.strings.<key>`. The app registers [Strings.delegate] and
/// [Strings.delegate.supportedLocales] in its `MaterialApp`.
library;

export 'generated/l10n.dart';
export 'src/strings_context.dart';
